"""update column in events table params[dict] -> source[str]

Revision ID: 033cacac4a55
Revises: e2735d4a5769
Create Date: 2025-08-31 21:30:42.605969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '033cacac4a55'
down_revision: Union[str, None] = 'e2735d4a5769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('source', sa.String(), nullable=False))
    op.drop_column('events', 'params')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('events', 'source')
    # ### end Alembic commands ###
