"""update event colum

Revision ID: 053241304666
Revises: f1cbd0f7a315
Create Date: 2025-07-02 18:15:58.836112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053241304666'
down_revision: Union[str, None] = 'f1cbd0f7a315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('event', sa.JSON(), nullable=False))
    op.drop_column('scenarios', 'event_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('scenarios', 'event')
    # ### end Alembic commands ###
