"""Add owner_email to scenarios table

Revision ID: 06c0431f8ac9
Revises: 4bd0c1b8f053
Create Date: 2025-07-14 02:17:54.902072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c0431f8ac9'
down_revision: Union[str, None] = '4bd0c1b8f053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('owner_email', sa.String(), nullable=False))
    op.create_index(op.f('ix_scenarios_owner_email'), 'scenarios', ['owner_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_owner_email'), table_name='scenarios')
    op.drop_column('scenarios', 'owner_email')
    # ### end Alembic commands ###
