"""added new column chat_id

Revision ID: 3710f6f9bde5
Revises: fd2a023a61a2
Create Date: 2025-07-04 16:04:19.914610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3710f6f9bde5'
down_revision: Union[str, None] = 'fd2a023a61a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('chat_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'chat_id')
    # ### end Alembic commands ###
