"""change

Revision ID: a2f6f631773e
Revises: ddfbc42bb4a0
Create Date: 2025-07-05 00:14:30.958421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f6f631773e'
down_revision: Union[str, None] = 'ddfbc42bb4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenarios', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenarios', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
