"""update table scenarios, added three column

Revision ID: f1cbd0f7a315
Revises: 81c3854404b2
Create Date: 2025-07-02 15:25:47.910034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cbd0f7a315'
down_revision: Union[str, None] = '81c3854404b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('event_type', sa.String(), nullable=False))
    op.add_column('scenarios', sa.Column('conditions', sa.JSON(), nullable=False))
    op.add_column('scenarios', sa.Column('actions', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'actions')
    op.drop_column('scenarios', 'conditions')
    op.drop_column('scenarios', 'event_type')
    # ### end Alembic commands ###
